# Generated by Django 6.0.6 on 2026-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('Boarding', 'Boarding'), ('Day', 'Day'), ('Mixed', 'Mixed')], max_length=20)),
                ('ownership', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Faith-Based', 'Faith-Based')], max_length=20)),
                ('school_fees', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
