# Generated by Django 6.0.6 on 2026-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_image_alter_school_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_performance',
            field=models.TextField(blank=True, help_text='Describe academic performance or achievements.'),
        ),
        migrations.AddField(
            model_name='school',
            name='facilities',
            field=models.TextField(blank=True, help_text="List the school's facilities."),
        ),
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.TextField(blank=True, help_text='List the main subjects offered.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Faith-Based', 'Faith-Based')], max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_fees',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
