# Generated by Django 6.0.6 on 2026-08-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_academic_performance_school_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_score',
            field=models.PositiveIntegerField(default=0, help_text='Academic score used for rankings.'),
        ),
        migrations.AddField(
            model_name='school',
            name='innovation_score',
            field=models.PositiveIntegerField(default=0, help_text='Science and innovation score used for rankings.'),
        ),
        migrations.AddField(
            model_name='school',
            name='sports_score',
            field=models.PositiveIntegerField(default=0, help_text='Sports score used for rankings.'),
        ),
    ]
