# Generated by Django 6.0.6 on 2026-08-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_academic_score_school_innovation_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/')),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='innovation_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='sports_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SchoolSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(blank=True, help_text='Important achievements in this sport.')),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='schools.school')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.sport')),
            ],
        ),
    ]
