# Generated by Django 6.0.6 on 2026-08-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_sport_alter_school_academic_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='competitions/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_performance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='subjects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolsport',
            name='achievement',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SchoolCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('achievement', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_schools', to='schools.competition')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='schools.school')),
            ],
        ),
    ]
