# Generated by Django 6.0.6 on 2026-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_competition_alter_school_academic_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subjects', models.TextField(blank=True, help_text='Recommended subjects or school subjects.')),
                ('skills', models.TextField(blank=True, help_text='Important skills for this career.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/')),
            ],
        ),
        migrations.CreateModel(
            name='TVETProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entry_requirements', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tvet/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
